### PR TITLE
Hotfix/update certificates #70

### LINKED ISSUE #70: update certificates which are used in test
Tests are failing due to expired certificates in repository, update them 

image

### PR DESCRIPTION
**Pull request by mrtrkmn**
- [x] a script which automatically generates localhost
- [x] workflow is updated
Closes #70

### CODE REVIEW

**Comment by mrtrkmn** [comment]
I tried placing `openssl` command to run directly when jobs started however GitHub Actions complained about usage of `/dev/urandom`, therefore, placed them as link as usual.

**Comment by Mikkelhost** [comment]
So the generation script is unused in the tests or?

**Comment by mrtrkmn** [comment]
> So the generation script is unused in the tests or?

Yes it is not used due to some limitation of GitHub Actions. I have tried to integrate it, however complained about generating rnd file on place. 

In case certificates will be a problem in long run, then the script can be used to generate easily. 

I actually forgot to include domain.ext file  to repo, which is required to generate certificates. 

@Mikkelhost

**Comment by mrtrkmn** [comment]
The script is really useful, since you can define as many domains as you want in `domains.ext` file, then generate certificates which cover all mentioned domains. 

In multi-dns scenario the file (domains.ext) would look like as follows:


```bash
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = localhost:50051
DNS.2 = mylocalhost
DNS.3 = localhaaukins
```

I think, this script can also be used for other parts of the project to test HTTPS connection in local as well.

**Review by Mikkelhost — COMMENTED** [review]
Can be merged :)

**Review by Mikkelhost — APPROVED** [review]

**Pull request merged**
